using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Diagnostics.Tracing;
using System.Linq;
using System.Security;
using System.Text;
using System.Threading.Tasks;

namespace TEST
{
    internal class Concurso
    {
        public string nombre_c;
        public string nombre_p;
        public string nombre_d;
        public int precio_c;
        public string status_c;
        public string calendar_c;
            public Concurso(string nombre_concurso, string persona, String dependencia, int precio, string status, string calendar)
        {
            nombre_c = nombre_concurso;
            nombre_p = persona;
            nombre_d = dependencia;
            precio_c = precio;
            status_c = status;
            calendar_c=calendar;
        }

        public void agregar_bd()
        {
            if (nombre_c != null && nombre_p != null && nombre_d != null && precio_c > 0 && status_c != null && calendar_c != null)
            {   
                //Creting a insert query with the data obtained from the UI 

                string insert_query = "insert into concurso values('" + nombre_c + "','" + nombre_p + "','" + nombre_d + "'," + precio_c + ",'" + status_c + "','" + calendar_c + "')";
                
                //MessageBox.Show(insert_query);

                //Using the authomatic string connection generated by Visual studio in order to establish the conecction to the database

                string database_conection = "Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=C:\\Users\\ad_ri\\source\\repos\\TEST\\TEST\\Database1.mdf;Integrated Security=True";
               
                using (SqlConnection connection = new SqlConnection(database_conection))
                {
                    try
                    {
                        connection.Open();
                        //MessageBox.Show("Conexion exitosa");
                        SqlCommand insert_command = new SqlCommand(insert_query, connection);
                        MessageBox.Show(insert_query);
                        insert_command.ExecuteNonQuery();
                        insert_command.Dispose();


                    }
                    catch (Exception e)
                    {
                        Console.Write("Error en conexion de DB", e);
                    }
                }
            }
            else
            {
                MessageBox.Show("Porfavor completa todos los datos");
            }
            ;

            
        }


    }
}